name: Generate Podcast Feeds
on: [push]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repo
        uses: action/checkout@v3
      - name: Run Feed Generator
        uses: Selene-ss/podcast-generator@main
